apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  MYSERVICE2_BASE_URL: http://myservice2:8080
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tododb
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info
