apiVersion: v1
kind: ServiceAccount
metadata:
  name: myservice
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myservice2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
